### ISSUE TITLE
ライセンス違反と思しきコードです

### ISSUE THREAD

**Issue by Nyanyan** [Asari-Science/othello#1]
こちらのレポジトリにあるコードに、元々私が書いたコードを無断でライセンスに違反して流用している可能性があるものを見つけました。事実関係の確認をお願いします。

私の見つけた範囲でわかりやすいものを2つ挙げます。
該当コード1: https://github.com/Asari-Science/othello/blob/main/index.html
私の書いたコード1: https://github.com/Nyanyan/Egaroucid_Web_Ver/blob/master/docs/index.html

該当コード2: https://github.com/Asari-Science/othello/blob/main/assets/js/script.js
私の書いたコード2: https://github.com/Nyanyan/Egaroucid_Web_Ver/blob/master/docs/assets/js/script.js

コードの流用を認める場合は以下をお読みください。
私が特に問題に感じているのは、該当コード1でコピーライトがつけられているところです(https://github.com/Asari-Science/othello/blob/main/index.html#L72)。
私もNo Licenseで公開したのは紛らわしかったと反省をしています。流用について特に妨げるつもりはないのですが、ライセンス周りについて相談をお願いします。

**Comment by Asari-Science** [comment]
申し訳ありません。友達とwasmを利用したWebページの作り方について学んでいたところだったので、ライセンスがなかったからと、調子に乗りすぎてしました。コピーライトはおそらく、いつもの癖でつけてしまった可能性があります。
このままリポジトリを残しておくのは倫理的に良くないと思ったので削除を検討しているのですが、いかがでしょうか？

**Comment by Nyanyan** [comment]
返信ありがとうございます。前述の通り、流用や利用について妨げる意図は特になく、コピーライトについて気になったのでご連絡差し上げました。レポジトリについてですが、私の元のレポジトリをこの件の後にGPL-v3ライセンスで公開し直しましたので、消さなくてもこれに沿った形で使っていただければ幸いです。

**Comment by Asari-Science** [comment]
了解しました。しかしながら、残しておくことに後ろめたい気持ちを感じているので、一旦コピーライトを削除し、その上でリポジトリも何日かあとに削除しようと思います。

**Comment by Nyanyan** [comment]
承知しました。よろしくお願いします。
